
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando fase de pre-construcci贸n..."
      - echo "Iniciando sesi贸n en Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 253490770873.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo "Fase de construcci贸n iniciada en `date`"
      - echo "Construyendo la imagen Docker..."
      - docker build -t mi-aplicacion .
      - echo "Etiquetando la imagen Docker..."
      - docker tag mi-aplicacion:latest 253490770873.dkr.ecr.us-east-2.amazonaws.com/mi-aplicacion:latest
  post_build:
    commands:
      - echo "Fase de post-construcci贸n iniciada en `date`"
      - echo "Empujando la imagen Docker al Amazon ECR..."
      - docker push 253490770873.dkr.ecr.us-east-2.amazonaws.com/mi-aplicacion:latest
      - echo "Imagen empujada exitosamente"
artifacts:
  files:
    - '**/*'
  discard-paths: yes

